### ISSUE TITLE
Review for lodash v3

### ISSUE THREAD

**Issue by jdalton** [lodash/grunt-lodash#15]
Lo-Dash v3 has several changes in support for custom builds.

* It allows `lodash modularize exports=es6`
* It drops support for `lodash underscore`
* It has singular category names like `array` instead of `arrays`<br>(though I'm adding aliases for the old style)
* Some methods have changed category

grunt-lodash should be reviewed for compatibility.

**Comment by jdalton** [comment]
@phated to test locally use the edge `lodash-cli` and and git clone `lodash-compat` into its `node_modules` folder and `npm i` from the root of `lodash-cli`.

**Comment by jdalton** [comment]
Can this be closed now?

**Comment by phated** [comment]
I haven't gotten around to merging and updating.  Real work, ya know?

**Comment by jdalton** [comment]
Ok cool!

**Comment by phated** [comment]
All set in master, travis is running and just need to npm publish
