### ISSUE TITLE
Review and update deps.

### ISSUE THREAD

**Issue by jdalton** [lodash/grunt-lodash#18]
Just some house cleaning. Review and update deps.

**Comment by phated** [comment]
reviewed, not required

**Comment by jdalton** [comment]
Cool. Did you also review the devDeps? I noticed several are behind. For example `semver` is now at `4.2.0` but we're using `~2.1.0` but I donno if it's because of some compat issue.

**Comment by jan4dev** [comment]
Did you plan on updating the lodash version too ? It would also be cool to be able to choose the lodash version since v3 was released.

**Comment by d10** [comment]
@jan4dev: The lodash version is already at 3.0.

@jdalton: can this be closed after commit 9d8ad86b77bee1a64fdd7126bbcabc32c9822778?
