### ISSUE TITLE
feature req: introspecting code to check which functions are used

### ISSUE THREAD

**Issue by gebrits** [lodash/grunt-lodash#19]
One of the nice things of a grunt pipeline imho is optimizing the heck out of delivered assets. 
The following feature request would be great in this light:  to have a build step  inspect the app-code and infer which lodash functions are used. These are used to dynamically create a lodash build that only contains the functions used. 

What do you think?

**Comment by jdalton** [comment]
It may be outside the scope of this plugin. There's [find-used-lodash](https://www.npmjs.com/package/find-used-lodash) which may help.

**Comment by phated** [comment]
I agree that this is out of scope.  In npm release of 3.0, you can just do `require('lodash/collection/forEach')`, which is better suited for slicing and dicing your builds.
